
name: 'styrstall_dbt'
version: '1.0.0'
config-version: 2

profile: 'styrstall_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"

models:
  styrstall_dbt:
    staging:
      +materialized: view
      +meta:
        dagster:
          group: staging

    intermediate:
      +materialized: view
      +meta:
        dagster:
          group: intermediate

    mart:
      +materialized: table
      +meta:
        dagster:
          group: mart
