styrstall_dbt:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1
      extensions:
        - spatial

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
