name: fetch stations
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:  # allows running manually from the Actions tab
jobs:
  fetch-stations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests azure-storage-blob

      - name: Execute Python script
        env:
          STYRSTALL_API_KEY: ${{ secrets.STYRSTALL_API_KEY }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        run: |
          python fetch_stations.py
