name: fetch stations
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:  # allows running manually from the Actions tab

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests azure-storage-blob
    - name: Get directory
      run: ls
    - name: Execute Python script
      env:
        STYRSTALL_API_KEY: ${{ secrets.STYRSTALL_API_KEY }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        python /home/runner/work/styrstall/workflows/fetch_stations.py
