name: fetch stations
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:  # allows running manually from the Actions tab

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests azure-storage-blob
    - name: Execute Python script
      env:
        STYRSTALL_API_KEY: ${{ secrets.STYRSTALL_API_KEY }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      run: |
        python fetch_stations.py
